grid_map_topic: /grid_map_tutorial_demo/grid_map

grid_map_visualizations:

  - name: elevation_points
    type: point_cloud
    params:
     layer: elevation

  - name: flat_grid
    type: flat_point_cloud
    params:
     height: 0.0
